# Postbox configuration.
EMAIL_ADDRESS:
EMAIL_USE_TLS: False
EMAIL_USE_SSL: True
EMAIL_HOST: smtp.qq.com
EMAIL_PORT: 465
EMAIL_HOST_USER:
EMAIL_HOST_PASSWORD:

# Database Link Information
DB_NAME: maxkb
DB_HOST: localhost
DB_PORT: 5432
DB_USER: root
DB_PASSWORD: testpwd
DB_ENGINE: django.db.backends.postgresql_psycopg2

EMBEDDING_MODEL_PATH: ./models
EMBEDDING_MODEL_NAME: sentence-transformers/all-MiniLM-L6-v2

DEBUG: false

TIME_ZONE: Asia/Shanghai
