# Generated by Django 4.1.10 on 2024-03-18 17:48

import common.field.vector_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='The key.id')),
                ('source_id', models.CharField(max_length=128, verbose_name='Resourcesid')),
                ('source_type', models.CharField(choices=[('0', 'The problem'), ('1', 'Paragraphs'), ('2', 'The title')], default='0', max_length=5, verbose_name='Type of Resource')),
                ('is_active', models.BooleanField(default=True, max_length=1, verbose_name='Is Available')),
                ('embedding', common.field.vector_field.VectorField(verbose_name='The quantity')),
                ('meta', models.JSONField(default=dict, verbose_name='The data')),
                ('dataset', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.dataset', verbose_name='Related Documents')),
                ('document', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.document', verbose_name='Related Documents')),
                ('paragraph', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='dataset.paragraph', verbose_name='Paragraphs related')),
            ],
            options={
                'db_table': 'embedding',
                'unique_together': {('source_id', 'source_type')},
            },
        ),
    ]
