# Generated by Django 4.1.10 on 2024-03-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creating time.')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Change time.')),
                ('type', models.IntegerField(choices=[(0, 'The mailbox'), (1, 'Private key.')], default=0, primary_key=True, serialize=False, verbose_name='Set the type.')),
                ('meta', models.JSONField(default=dict, verbose_name='Configuration of data')),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
    ]
