# Postbox configuration.
EMAIL_ADDRESS: ${EMAIL_ADDRESS}
EMAIL_USE_TLS: ${EMAIL_USE_TLS}
EMAIL_USE_SSL: ${EMAIL_USE_SSL}
EMAIL_HOST: ${EMAIL_HOST}
EMAIL_PORT: ${EMAIL_PORT}
EMAIL_HOST_USER: ${EMAIL_HOST_USER}
EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

# Database Link Information
DB_NAME: maxkb
DB_HOST: 127.0.0.1
DB_PORT: 5432
DB_USER: root
DB_PASSWORD: testpwd
DB_ENGINE: django.db.backends.postgresql_psycopg2
EMBEDDING_MODEL_PATH: ./models
EMBEDDING_MODEL_NAME: sentence-transformers/all-MiniLM-L6-v2

DEBUG: false