version: "3"
services:
  db:
    hostname: 127.0.0.1
    image: pgvector/pgvector:pg16
    ports:
     - 5432:5432
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=root
      - PGUSER=root
      - POSTGRES_PASSWORD=testpwd
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d vectordb -U root"]
    volumes:
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql